# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [19]:
import numpy as np

A = np.random.random_integers(0, 10, (3, 3))
B = np.random.random_integers(0, 10, (3, 3))
C = np.random.random_integers(0, 10, (3, 3))

print(np.dot(A, B+C))
print(' ')
print(np.dot(A, B) + np.dot(A, C))

[[175 155 218]
 [144  90 144]
 [143 155 192]]
 
[[175 155 218]
 [144  90 144]
 [143 155 192]]


/opt/conda/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:3: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/conda/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  after removing the cwd from sys.path.
/opt/conda/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  """


## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [20]:
print(np.dot(A, np.dot(B, C)))
print(' ')
print(np.dot(np.dot(A, B),C))

[[1715  864 1585]
 [ 945  531  945]
 [1785  824 1545]]
 
[[1715  864 1585]
 [ 945  531  945]
 [1785  824 1545]]


## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [21]:
print(np.dot(A, B))
print(np.dot(B, A))

[[76 85 95]
 [54 45 54]
 [66 95 93]]
[[ 66  21 102]
 [ 64  19 151]
 [ 84  24 129]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [29]:
x = np.array([[2], [6], [7]])
y = np.array([[3], [5], [9]])

print(np.dot(np.transpose(x), y))
print(' ')
print(np.dot(np.transpose(y), x))

[[99]]
 
[[99]]


#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [30]:
print(np.transpose(np.dot(A, B)))
print(' ')
print(np.dot(np.transpose(B), np.transpos))

AttributeError: module 'numpy' has no attribute 'tranpsose'

## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 